[package]
name = "unavi-world-host"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
axum-server.workspace = true
axum.workspace = true
base64.workspace = true
clap.workspace = true
didkit.workspace = true
dwn.workspace = true
serde.workspace = true
serde_json.workspace = true
surrealdb = { workspace = true, features = ["kv-surrealkv"] }
tokio.workspaced = true
tracing.workspace = true
wired-protocol = { path = "../wired-protocol" }
