[package]
name = "unavi-wasm-runtime"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
bevy = "0.12.0"
bevy_rapier3d = { version = "0.23.0", features = ["simd-stable"] }
tracing = "0.1.40"
unavi-system-bindgen = { path = "../../wasm/unavi-system/bindgen" }
wasmtime = { version = "15.0.0", features = ["component-model"] }

[dev-dependencies]
tracing-subscriber = "0.3.18"
