[package]
name = "unavi-wasm-runtime"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasmtime = { version = "15.0.0", features = ["component-model"] }
unavi-system-api = { path = "../unavi-system-api" }
