cargo-features = ["per-package-target"]

[package]
name = "wired-host"
default-target = "wasm32-unknown-unknown"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.15.0"
