[workspace]
resolver = "2"
members = [
  "components/*",
  "crates/*",
]

[workspace.package]
version = "0.0.2"
edition = "2021"
repository = "https://github.com/unavi-xyz/unavi"
license = "GPL-3.0-or-later"

[workspace.lints.clippy]
type_complexity = "allow"

[workspace.dependencies]
wired-protocol = { path = "crates/wired-protocol" }

clap = { version = "4.5.4", features = ["derive"] }
didkit = { version = "0.6.0", default-features = false, features = ["ed25519"] }
dwn = "0.0.6"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
surrealdb = { version = "1.3.1", default-features = false }
tokio = { version = "1.37.0", features = ["macros", "rt", "time"]}
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
wit-bindgen-rt = { version = "0.23.0", features = ["bitflags"] }
wtransport = "0.1.8"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true

[profile.wasm-release]
inherits = "release"
codegen-units = 1
opt-level = "z"

[patch.crates-io]
wasm-bridge = { git = "https://github.com/kayhhh/wasm-bridge.git", branch = "sync" }
wasm-bridge-wasi = { git = "https://github.com/kayhhh/wasm-bridge.git", branch = "sync" }
