[workspace]
resolver = "2"
members = [
  "components/*",
  "crates/*",
]

[workspace.package]
version = "0.0.2"
edition = "2021"
repository = "https://github.com/unavi-xyz/unavi"
license = "GPL-3.0-or-later"

[workspace.lints.clippy]
type_complexity = "allow"

[workspace.dependencies]
bevy = "0.13.1"
bitflags = "2.5.0"
didkit = { version = "0.6.0", default-features = false, features = ["ed25519"] }
dwn = "0.0.5"
surrealdb = { version = "1.3.1", default-features = false, features = ["kv-speedb"] }
tokio = { version = "1.37.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
wasm-bindgen = "=0.2.91"
wit-bindgen-rt = "0.20.0"
wtransport = "0.1.8"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true

[profile.wasm-release]
inherits = "release"
codegen-units = 1
opt-level = "z"

[patch.crates-io]
dwn = { git = "https://github.com/unavi-xyz/dwn.git" }
wasm-bridge = { git = "https://github.com/kayhhh/wasm-bridge.git", branch = "wasmtime-18" }
wasm-bridge-wasi = { git = "https://github.com/kayhhh/wasm-bridge.git", branch = "wasmtime-18" }
