[workspace]
resolver = "2"
members = [
  "components/*",
  "crates/*",
]

[workspace.package]
version = "0.0.2-beta.23"
edition = "2021"
repository = "https://github.com/unavi-xyz/unavi"
license = "GPL-3.0-or-later"

[workspace.lints.clippy]
type_complexity = "allow"

[workspace.dependencies]
axum = "0.7.4"
bevy = "0.13.0"
bitflags = "2.4.2"
tokio = { version = "1.34.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
wasm-bindgen = "=0.2.91"
wit-bindgen-rt = "0.20.0"
wtransport = "0.1.8"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true

[profile.wasm-release]
inherits = "release"
codegen-units = 1
opt-level = "z"
