[package]
name = "unavi-dwn"
publish = false
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
bevy.workspace = true
bevy_async_task.workspace = true
dwn.workspace = true
surrealdb.workspace = true
