[package]
name = "unavi-player"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
avian3d.workspace = true
bevy-tnua = "0.19.0"
bevy-tnua-avian3d = "0.1.0"
bevy.workspace = true
unavi-constants = { path = "../unavi-constants" }
unavi-scripting = { path = "../unavi-scripting" }

[target.'cfg(target_family = "wasm")'.dependencies]
web-sys = { workspace = true, features = ["Navigator", "Window"] }
