[package]
name = "unavi-player"
publish = false
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
avian3d.workspace = true
bevy.workspace = true
bevy_vr_controller.workspace = true
bevy_vrm.workspace = true
unavi-constants = { path = "../unavi-constants", features = ["physics"] }
