[package]
name = "unavi-world"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
base64.workspace = true
bevy.workspace = true
bevy_async_task.workspace = true
bevy_vrm.workspace = true
bevy_xpbd_3d.workspace = true
dwn.workspace = true
serde_json.workspace = true
thiserror.workspace = true
unavi-dwn = { path = "../unavi-dwn" }
wired-social = { path = "../wired-social" }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
bevy_atmosphere = "0.9.1"
