[package]
name = "unavi-world"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
bevy.workspace = true
bevy_vrm = "0.0.10"
bevy_xpbd_3d.workspace = true
unavi-dwn = { path = "../unavi-dwn" }
