[package]
name = "unavi-app"
publish = false
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[package.metadata.wix]
eula = false

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
avian3d.workspace = true
bevy = { workspace = true, features = ["wayland"] }
clap.workspace = true
directories.workspace = true
dwn.workspace = true
tracing.workspace = true
unavi-networking = { path = "../unavi-networking" }
unavi-player = { path = "../unavi-player" }
unavi-scripting = { path = "../unavi-scripting" }
unavi-settings = { path = "../unavi-settings" }
unavi-world = { path = "../unavi-world" }

[target.'cfg(target_family = "wasm")'.dependencies]
surrealdb = { workspace = true, features = ["kv-indxdb"] }
tokio.workspace = true
wasm-bindgen-futures.workspace = true
wasm-bindgen.workspace = true
web-sys = { workspace = true, features = [
  "Location",
  "UrlSearchParams",
  "Window",
] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
bevy_oxr = "0.3.0"
reqwest.workspace = true
self_update = "0.41.0"
surrealdb = { workspace = true, features = ["kv-mem", "kv-surrealkv"] }
tempfile = "3.12.0"
tokio.workspace = true
zip = { version = "2.2.0", default-features = false, features = ["deflate"] }

[build-dependencies]
unavi-constants = { path = "../unavi-constants" }
