[package]
name = "unavi-app"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[features]
disable-cert-validation = ["wtransport/dangerous-configuration"]

[lints]
workspace = true

[dependencies]
bevy.workspace = true
bevy-async-task = "1.3.0"
bevy_rapier3d = { version = "0.23.0", features = ["simd-stable"] }
bevy_vrm = "0.0.6"
tracing = "0.1.40"
# unavi-system-bindgen = { path = "../../wasm/unavi-system/bindgen" }
# wired-script-bindgen = { path = "../../wasm/wired-script/bindgen" }
xwt = "0.3.0"
xwt-core = "0.2.0"

[target.'cfg(target_family = "wasm")'.dependencies]
xwt-web-sys = "0.3.1"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
wasmtime = { version = "15.0.0", features = ["component-model"] }
wtransport = "0.1.8"
