[package]
name = "unavi-app"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[features]
default = []
self_update = ["dep:self_update"]

[lints]
workspace = true

[dependencies]
bevy = { workspace = true, features = ["wayland"] }
bevy_xpbd_3d.workspace = true
clap.workspace = true
dwn.workspace = true
tracing.workspace = true
unavi-dwn = { path = "../unavi-dwn" }
unavi-networking = { path = "../unavi-networking" }
unavi-player = { path = "../unavi-player" }
unavi-scripting = { path = "../unavi-scripting" }
unavi-settings = { path = "../unavi-settings" }
unavi-world = { path = "../unavi-world" }

[target.'cfg(target_family = "wasm")'.dependencies]
surrealdb = { workspace = true, features = ["kv-indxdb"] }
tokio.workspace = true
wasm-bindgen-futures.workspace = true
wasm-bindgen.workspace = true
web-sys = { workspace = true, features = ["Location", "UrlSearchParams", "Window"] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
anyhow.workspace = true
reqwest.workspace = true
self_update = { version = "0.39.0", features = ["archive-zip"], optional = true }
semver.workspace = true
surrealdb = { workspace = true, features = ["kv-surrealkv"] }
tokio = { workspace = true, features = ["rt-multi-thread"] }
zip = { version = "1.1.1", default-features = false, features = ["deflate"] }
