[package]
name = "unavi-app"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = "1.0.75"
bevy.workspace = true
bevy_rapier3d = { version = "0.23.0", features = ["simd-stable"] }
bevy_vrm = "0.0.6"
serde = { version = "1.0.193", features = ["derive"] }
tokio = { version = "1.34.0", features = ["full"] }
tracing = "0.1.40"
unavi-system-bindgen = { path = "../../wasm/unavi-system/bindgen" }
wired-script-bindgen = { path = "../../wasm/wired-script/bindgen" }
wtransport = "0.1.8"
xwt = "0.3.0"
xwt-core = "0.2.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
wasmtime = { version = "15.0.0", features = ["component-model"] }
