[package]
name = "wired-protocol"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
dwn.workspace = true
semver = "1.0.22"
serde_json.workspace = true
