[package]
name = "unavi-server"
publish = false
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
async-recursion = "1.1.1"
clap.workspace = true
dwn.workspace = true
surrealdb = { workspace = true, features = ["kv-mem", "kv-surrealkv"] }
tokio = { workspace = true, features = ["rt-multi-thread", "signal"] }
tracing-subscriber = "0.3.18"
tracing.workspace = true
unavi-social-server = { path = "../unavi-social-server" }
unavi-world-host = { path = "../unavi-world-host" }
unavi-world-server = { path = "../unavi-world-server" }

[dev-dependencies]
port_scanner = "0.1.5"
reqwest.workspace = true
serde_json.workspace = true
tracing-test.workspace = true
