[package]
name = "unavi-server"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-recursion = "1.1.1"
clap.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "signal"] }
tracing-subscriber = "0.3.18"
tracing.workspace = true
unavi-social-server = { path = "../unavi-social-server" }
unavi-world-host = { path = "../unavi-world-host" }
unavi-world-server = { path = "../unavi-world-server" }

[dev-dependencies]
dwn.workspace = true
port_scanner = "0.1.5"
reqwest.workspace = true
serde_json.workspace = true
surrealdb = { workspace = true, features = ["kv-mem"] }
tracing-test = { version = "0.2.4", features = ["no-env-filter"] }
wired-social = { path = "../wired-social" }
wtransport = { workspace = true, features = ["dangerous-configuration"] }
