[package]
name = "unavi-server"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[lints]
workspace = true

[features]
default = ["auth", "web", "world"]
axum = [
  "dep:axum",
]
auth = [
  "axum",
  "dep:unavi-server-auth",
]
web = [
  "axum",
  "dep:unavi-server-web",
]
world = [
  "dep:unavi-server-world",
]

[dependencies]
tokio = { version = "1.34.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

axum = { version = "0.6.20", optional = true }
unavi-server-auth = { path = "../unavi-server-auth", optional = true }
unavi-server-web = { path = "../unavi-server-web", optional = true }
unavi-server-world = { path = "../unavi-server-world", optional = true }
