[package]
name = "unavi-server"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
axum = "0.7.5"
axum-server = "0.6.0"
clap.workspace = true
didkit.workspace = true
dwn-server = "0.0.5"
dwn.workspace = true
rcgen = "0.13.0" 
serde.workspace = true
serde_json.workspace = true
surrealdb = { workspace = true, features = ["kv-speedb"] }
time = "0.3.30"
tokio = { workspace = true, features = ["rt-multi-thread"] }
tower-http = { version = "0.5.2", features = ["fs"] }
tracing-subscriber.workspace = true
tracing.workspace = true
wired-protocol.workspace = true
wtransport.workspace = true
