[package]
name = "unavi-server"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
axum = "0.7.5"
axum-server = "0.6.0"
clap.workspace = true
didkit.workspace = true
dwn-server = "0.0.6"
dwn.workspace = true
rcgen = "0.13.0" 
serde.workspace = true
serde_json.workspace = true
surrealdb = { workspace = true, features = ["kv-surrealkv"] }
tokio = { workspace = true, features = ["rt-multi-thread", "signal"] }
tracing-subscriber = "0.3.18"
tracing.workspace = true
wired-protocol = { path = "../wired-protocol" }
wtransport.workspace = true
