[package]
name = "unavi-server"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[lints]
workspace = true

[features]
default = ["social", "web", "world"]
social = [
  "dep:unavi-server-social",
]
web = [
  "dep:unavi-server-web",
  "dep:axum",
]
world = [
  "dep:unavi-server-world",
]

[dependencies]
tokio = { version = "1.34.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
unavi-server-social = { path = "../unavi-server-social", optional = true }
unavi-server-web = { path = "../unavi-server-web", optional = true }
unavi-server-world = { path = "../unavi-server-world", optional = true }

axum = { version = "0.6.20", optional = true }
