[package]
name = "unavi-server"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
axum = "0.7.5"
axum-server = "0.6.0"
clap = { version = "4.5.4", features = ["derive"] }
didkit.workspace = true
dwn-server = "0.0.5"
dwn.workspace = true
rcgen = "0.13.0" 
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
surrealdb.workspace = true
time = "0.3.30"
tokio.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
wtransport.workspace = true
