[package]
name = "xwt-futures-io"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
futures-io = "0.3.30"
xwt-core.workspace = true
