[package]
name = "xwt-futures-io"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
futures-io = "0.3.30"
tracing.workspace = true
xwt-core.workspace = true
