[package]
name = "unavi-constants"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
bevy_xpbd_3d.workspace = true
