[package]
name = "unavi-constants"
publish = false
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[features]
default = []
physics = ["dep:avian3d"]

[dependencies]
avian3d = { workspace = true, optional = true }
