[package]
name = "wired-social"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
dwn.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
jsonschema = { version = "0.17.1", features = ["draft201909", "draft202012"] }
