[package]
name = "unavi-server-dwn"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
tokio = { version = "1.34.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
