[package]
name = "unavi-system-bindgen"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
wasmtime = { version = "15.0.0", features = ["component-model"] }
