[package]
name = "unavi-scene"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen-rt.workspace = true

[package.metadata.component]
package = "unavi:scene"

[package.metadata.component.target.dependencies]
"wired:input" = { path = "../../wired-protocol/spatial/wit/wired-input" }
"wired:math" = { path = "../../wired-protocol/spatial/wit/wired-math" }
"wired:physics" = { path = "../../wired-protocol/spatial/wit/wired-physics" }
"wired:scene" = { path = "../../wired-protocol/spatial/wit/wired-scene" }
