[package]
name = "test-wired-dwn"
publish = false
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen-rt.workspace = true

[package.metadata.component]
package = "test:wired-dwn"

[package.metadata.component.target.dependencies]
"wired:dwn" = { path = "../../wired-protocol/spatial/wit/wired-dwn" }
"wired:log" = { path = "../../wired-protocol/spatial/wit/wired-log" }
"wired:script" = { path = "../../wired-protocol/spatial/wit/wired-script" }
