[build]
target = "wasm32-unknown-unknown"

[target.'cfg(target_family = "wasm")']
rustflags = [
  "--cfg=web_sys_unstable_apis", # xwt-web-sys
] 

[target.'cfg(not(target_family = "wasm"))']
rustflags = [
  "--cfg=surrealdb_unstable" # surreal-kv
]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
