[package]
name = "wired-world"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
capnp = "0.19.4"

[build-dependencies]
capnpc = "0.19.0"
