[package]
name = "unavi-system"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
wit-bindgen = { version = "0.16.0", default-features = false, features = ["realloc"] }

[package.metadata.component]
package = "component:unavi-system"

[package.metadata.component.dependencies]
