[package]
name = "test-wired-gltf"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen-rt.workspace = true

[dev-dependencies]
bevy.workspace = true
unavi-scripting = { path = "../../crates/unavi-scripting" }

[package.metadata.component]
package = "test:wired-gltf"

[package.metadata.component.target.dependencies]
"wired:gltf" = { path = "../../wired-protocol/spatial/wit/wired-gltf" }
"wired:log" = { path = "../../wired-protocol/spatial/wit/wired-log" }
"wired:math" = { path = "../../wired-protocol/spatial/wit/wired-math" }
"wired:physics" = { path = "../../wired-protocol/spatial/wit/wired-physics" }
"wired:script" = { path = "../../wired-protocol/spatial/wit/wired-script" }
