[package]
name = "unavi-world-server"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
rcgen = "0.13.1"
tokio.workspace = true
tracing.workspace = true
wtransport.workspace = true
