[package]
name = "unavi-avatar"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
bevy.workspace = true
bevy_vrm.workspace = true

[dev-dependencies]
bevy_panorbit_camera = "0.18.2"
