[package]
name = "unavi-native"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
bevy.workspace = true
unavi-app = { path = "../unavi-app" }
