[package]
name = "unavi-shapes"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
parry3d = "0.16.1"
wit-bindgen-rt.workspace = true

[package.metadata.component]
package = "unavi:shapes"

[package.metadata.component.target.dependencies]
"wired:input" = { path = "../../wired-protocol/spatial/wit/wired-input" }
"wired:math" = { path = "../../wired-protocol/spatial/wit/wired-math" }
"wired:physics" = { path = "../../wired-protocol/spatial/wit/wired-physics" }
"wired:scene" = { path = "../../wired-protocol/spatial/wit/wired-scene" }
