[package]
name = "example-wired-gltf"
version.workspace = true
edition.workspace = true
repository.workspace = true
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
glam = "0.28.0"
wit-bindgen-rt.workspace = true

[dev-dependencies]
bevy.workspace = true
unavi-scripting = { path = "../../crates/unavi-scripting" }

[package.metadata.component]
package = "example:wired-gltf"

[package.metadata.component.target.dependencies]
"unavi:shapes" = { path = "../unavi-shapes/wit" }
"wired:gltf" = { path = "../../wired-protocol/spatial/wit/wired-gltf" }
"wired:log" = { path = "../../wired-protocol/spatial/wit/wired-log" }
"wired:math" = { path = "../../wired-protocol/spatial/wit/wired-math" }
"wired:script" = { path = "../../wired-protocol/spatial/wit/wired-script" }
