[package]
name = "example-wired-input"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen-rt.workspace = true

[package.metadata.component]
package = "example:wired-input"

[package.metadata.component.target.dependencies]
"unavi:shapes" = { path = "../unavi-shapes/wit" }
"wired:gltf" = { path = "../../wired-protocol/spatial/wit/wired-gltf" }
"wired:input" = { path = "../../wired-protocol/spatial/wit/wired-input" }
"wired:log" = { path = "../../wired-protocol/spatial/wit/wired-log" }
"wired:math" = { path = "../../wired-protocol/spatial/wit/wired-math" }
"wired:physics" = { path = "../../wired-protocol/spatial/wit/wired-physics" }
"wired:script" = { path = "../../wired-protocol/spatial/wit/wired-script" }
