name: Build Windows

on:
  workflow_call:
    inputs:
      channel:
        description: The channel to build.
        required: true
        type: string
      ref:
        description: The ref to build.
        required: true
        type: string

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        package: [unavi-app, unavi-server]
    name: x86_64-windows.${{ matrix.package }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}
          submodules: true

      - uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install capnproto wixtoolset

      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - run: cargo install cargo-component
      - run: cargo install cargo-wix
      - run: cargo install wac-cli

      - name: Build package
        run: |
          cargo wix -p ${{ matrix.package }} --target x86_64-pc-windows-msvc
          mkdir result
          mv target/x86_64-pc-windows-msvc/release/*.exe result
          cp crates/${{ matrix.package }}/README.md result
          cp LICENSE result
        env:
          UNAVI_REGISTRY_DID: ${{ inputs.channel == 'stable' && 'app' || inputs.channel }}.unavi.xyz

      - name: Create zip
        run: Compress-Archive -Path result/* -DestinationPath ${{ matrix.package }}.x86_64-windows.zip

      - name: Create msi
        run: cp target/x86_64-pc-windows-msvc/release/*.msi ${{ matrix.packages }}.x86-64_windows.msi

      - uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.package }}.x86_64-windows
          path: ${{ matrix.package }}.x86_64-windows.zip
          retention-days: 1

      - uses: actions/upload-artifact@v4
        with:
          name: build-installer-${{ matrix.package }}.x86_64-windows
          path: ${{ matrix.package }}.x86_64-windows.msi
          retention-days: 1
