name: "Get Build Matrix"

on:
  workflow_call:

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - id: set-matrix
        run: |
          matrix=$(nix eval --json .#githubActions.matrix)
          echo matrix=$matrix >> $GITHUB_OUTPUT
