name: "Build Web"

on:
  workflow_call:
    inputs:
      ref:
        description: "The ref to build."
        required: true
        type: string
  workflow_dispatch:

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}
          submodules: true

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - run: nix build .?submodules=1#web
      - run: find result -exec zip -r web.zip {} +

      - uses: actions/upload-artifact@v4
        with:
          name: build-web-${{ inputs.ref || github.ref }}
          path: web.zip
          retention-days: 1
