name: Build Nix

on:
  workflow_call:
    inputs:
      channel:
        description: The channel to build.
        required: true
        type: string
      ref:
        description: The ref to build.
        required: true
        type: string

jobs:
  nix-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}

      - uses: DeterminateSystems/nix-installer-action@main

      - id: set-matrix
        run: |
          matrix=$(nix eval --json .#githubMatrix.matrix)
          echo "Matrix: $matrix"
          echo matrix=$matrix >> $GITHUB_OUTPUT

  build-nix:
    needs: nix-matrix
    strategy:
      matrix: ${{ fromJSON(needs.nix-matrix.outputs.matrix) }}
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: AdityaGarg8/remove-unwanted-software@v4
        with:
          remove-android: true
          remove-cached-tools: true
          remove-codeql: true
          remove-dotnet: true
          remove-haskell: true

      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}
          submodules: true

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - run: nix build -L .?submodules=1#packages.${{ matrix.attr }}-${{ inputs.channel }}
      - run: |
          cp -rL result tmp
          chmod -R 755 tmp
          cd tmp
          zip -r ../${{ matrix.name }}.zip .

      - uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.name }}
          path: ${{ matrix.name }}.zip
          retention-days: 1
