name: "Build"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  nix-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - id: set-matrix
        run: |
          matrix=$(nix eval --json .#githubMatrix.matrix)
          echo matrix=$matrix >> $GITHUB_OUTPUT

  build-nix:
    needs:
      - nix-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.nix-matrix.outputs.matrix) }}
    name: ${{ matrix.attr }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          fetch-depth: 0

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - run: nix build .?submodules=1#packages.${{ matrix.attr }}
      - run: find result/bin -exec zip -r ${{ matrix.attr }}.zip {} +

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.attr }}
          path: ${{ matrix.attr }}.zip
          retention-days: 1

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        package: [unavi-app, unavi-server]
    name: x86_64-windows.${{ matrix.package }}
    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - run: mkdir result

      - if: ${{ matrix.package == 'unavi-app' }}
        name: Generate assets
        run: |
          cargo install cargo-component

          foreach ($component in Get-ChildItem -Path components) {
              cargo component build -p $component.Name --profile wasm-release
          }

          Get-ChildItem -Path "target/wasm32-wasi/wasm-release" -Recurse -File | Where-Object { $_.Name -like '*.wasm' } | ForEach-Object {
              Copy-Item -Path $_.FullName -Destination "assets/components" -Force
          }

          Copy-Item -Path "assets" -Destination "result" -Recurse -Force

      - name: Build package
        run: |
          cargo build -p ${{ matrix.package }} --release --target x86_64-pc-windows-msvc
          mv target/x86_64-pc-windows-msvc/release/*.exe result

      - run: Compress-Archive -Path result -DestinationPath x86_64-windows.${{ matrix.path }}.zip

      - uses: actions/upload-artifact@v4
        with:
          name: x86_64-windows.${{ matrix.path }}
          path: x86_64-windows.${{ matrix.path }}.zip
          retention-days: 1
