name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: AdityaGarg8/remove-unwanted-software@v3
        with:
          remove-android: true
          remove-codeql: true
          remove-docker-images: true
          remove-dotnet: true
          remove-haskell: true

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          submodules: true

      - uses: DeterminateSystems/flake-checker-action@v7

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: Swatinem/rust-cache@v2

      - run: nix run .?submodules=1#check-components
      - uses: EndBug/add-and-commit@v9
        with:
          message: "chore: generate component bindings"
          default_author: github_actions

      - run: nix develop -c cargo clippy --all-features --fix --no-deps
      - run: nix develop -c cargo fmt --all
      - run: nix develop -c prettier -w .
      - run: nix fmt .
      - run: nix run .#tf-format
      - uses: EndBug/add-and-commit@v9
        with:
          message: "chore: lint"
          default_author: github_actions

      - run: nix run .#generate-readme
      - uses: EndBug/add-and-commit@v9
        with:
          message: "chore: generate README"
          default_author: github_actions

      - run: nix develop -c cargo doc --workspace --all-features --no-deps
      - run: nix develop -c cargo test --workspace --all-features --all-targets
      - run: nix develop -c cargo test --workspace --all-features --doc
