name: "CI"

on:
  push:
  pull_request:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: Swatinem/rust-cache@v2
      - run: nix develop -c cargo component check
      - uses: EndBug/add-and-commit@v9
        with:
          message: "chore: generate wasm bindings"
          default_author: github_actions
      - run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  lint:
    needs:
      - generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          ref: ${{ needs.generate.outputs.sha }}
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: Swatinem/rust-cache@v2
      - run: nix develop -c cargo clippy --fix --no-deps
      - run: nix develop -c cargo fmt --all
      - run: nix develop -c prettier -w .
      - uses: EndBug/add-and-commit@v9
        with:
          message: "chore: lint"
          default_author: github_actions
      - run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  check:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: AdityaGarg8/remove-unwanted-software@v2
        with:
          remove-android: "true"
          remove-dotnet: "true"
          remove-haskell: "true"
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          ref: ${{ needs.lint.outputs.sha }}
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: Swatinem/rust-cache@v2
      - run: nix flake check ".?submodules=1" --all-systems
