name: Deploy Web

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      channel:
        required: true
        type: string
      ref:
        required: true
        type: string
  workflow_dispatch:

env:
  CHANNEL: ${{ inputs.channel || github.ref_name }}

concurrency:
  group: "deploy-web-${{ inputs.channel || github.ref_name }}"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}
          submodules: true

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - run: nix build .?submodules=1#web
      - run: |
          cp -rL result tmp
          cd tmp
          zip -r ../web.zip .

      - uses: actions/upload-artifact@v4
        with:
          name: build-web
          path: web.zip
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Create branch
        run: git checkout --orphan web-app/${{ env.CHANNEL }}

      - name: Clean directory
        run: |
          find . -mindepth 1 -maxdepth 1 -not -name '.git' -exec rm -rf {} \;

      - uses: actions/download-artifact@v4
        with:
          name: build-web

      - name: Unzip artifact
        run: |
          unzip web.zip
          rm web.zip

      - name: Commit changes
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Deploy web-app/${{ env.CHANNEL }}"

      - name: Push changes
        run: git push origin web-app/${{ env.CHANNEL }} --force
