name: Deploy

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      channel:
        type: string
        required: true
  workflow_dispatch:

env:
  CHANNEL: ${{ inputs.channel || github.ref_name }}

concurrency:
  group: "deploy-${{ inputs.channel || github.ref_name }}"
  cancel-in-progress: false

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: Swatinem/rust-cache@v2

      - run: nix build .#web && cp -rL result www

      - uses: s0/git-publish-subdir-action@develop
        env:
          BRANCH: "web-app/${{ env.CHANNEL }}"
          COMMIT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
          COMMIT_NAME: "github-actions[bot]"
          FOLDER: www
          GITHUB_TOKEN: ${{ github.token }}
          REPO: self
          SQUASH_HISTORY: true
          TARGET_DIR: www
