name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "deployment"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: Swatinem/rust-cache@v2
      - run: nix build .#web
      - run: cp -rL result/web www
      - uses: s0/git-publish-subdir-action@develop
        env:
          BRANCH: build/web-app
          COMMIT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
          COMMIT_NAME: "github-actions[bot]"
          FOLDER: www
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: self
          SQUASH_HISTORY: true
          TARGET_DIR: www
