name: Deploy

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      channel:
        type: string
        required: true
  workflow_dispatch:

env:
  CHANNEL: ${{ inputs.channel || github.ref_name }}

concurrency:
  group: "deploy-${{ inputs.channel || github.ref_name }}"
  cancel-in-progress: false

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: Swatinem/rust-cache@v2

      - run: nix build .#web

      - name: Publish to branch
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          # Remove all files besides our build output
          git rm -r .
          cp -rL result/* .

          git add .
          git commit -m "chore: deploy web-app/${{ env.CHANNEL }}"

          # Squash commits
          git rebase -i HEAD~2

          git push origin HEAD:web-app/${{ env.CHANNEL }}
