name: Deploy Server

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      channel:
        required: true
        type: string
      ref:
        required: true
        type: string
  workflow_dispatch:

env:
  TF_WORKSPACE: ${{ inputs.channel || github.ref_name }}

concurrency:
  group: "deploy-server-${{ inputs.channel || github.ref_name }}"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}
      DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{ inputs.ref || github.ref }}

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Apply Terraform
        run: nix run .?submodules=1#tf-apply ${{ env.TF_WORKSPACE }}

      - name: Deploy
        run: nix-shell -p deploy-rs --command "deploy .?submodules=1 --skip-checks"
