name: Deploy

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      channel:
        type: string
        required: true
  workflow_dispatch:

env:
  CHANNEL: ${{ inputs.channel || github.ref_name }}

concurrency:
  group: "deploy-${{ inputs.channel || github.ref_name }}"
  cancel-in-progress: false

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: Swatinem/rust-cache@v2

      - run: nix build .#web

      - name: Create branch
        run: git checkout --orphan web-app/${{ env.CHANNEL }}

      - name: Clean directory
        run: |
          git rm -r .
          cp -rL result/* .

      - name: Commit changes
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Deploy web-app/${{ env.CHANNEL }}"

      - name: Squash history
        run: git rebase -i HEAD~1

      - name: Push changes
        run: git push origin web-app/${{ env.CHANNEL }} --force
