name: Deploy

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      channel:
        type: string
        required: true
  workflow_dispatch:

concurrency:
  group: "deploy-${{ inputs.channel }}"
  cancel-in-progress: false

jobs:
  deploy-web:
    name: deploy-web-${{ inputs.channel }}
    runs-on: ubuntu-latest
    env:
      IS_MAIN: ${{ inputs.channel == 'main' || github.ref_name == 'main' }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: Swatinem/rust-cache@v2

      - if: env.IS_MAIN == true
        run: nix develop -c trunk build

      - if: env.IS_MAIN == false
        run: nix build .#web

      - run: cp -rL result www
      - uses: s0/git-publish-subdir-action@develop
        env:
          BRANCH: "web-app/${{ inputs.channel }}"
          COMMIT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
          COMMIT_NAME: "github-actions[bot]"
          FOLDER: www
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: self
          SQUASH_HISTORY: true
          TARGET_DIR: www
