name: "Release"

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true

concurrency:
  group: "release"
  cancel-in-progress: false

jobs:
  build-matrix:
    uses: ./.github/workflows/build-matrix.yml

  release-notes:
    runs-on: ubuntu-latest
    outputs:
      release-notes: ${{ steps.release-notes.outputs.release-notes }}
    steps:
      - name: Generate Release Notes
        id: release-notes
        uses: RedCrafter07/release-notes-action@v1.0.0
        with:
          tag-name: ${{ github.event.inputs.tag-name }}
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-artifacts:
    needs:
      - build-matrix
      - release-notes
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.build-matrix.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.attr }}
          path: ${{ matrix.attr }}.zip

      - uses: svenstaro/upload-release-action@v2
        with:
          asset_name: ${{ matrix.attr }}-${{ inputs.version }}.zip
          body: ${{ needs.release-notes.outputs.release-notes }}
          file: ${{ matrix.attr }}.zip
          prerelease: ${{ contains(inputs.version, 'beta') }}
          repo_token: ${{ github.token }}
          tag: ${{ inputs.version }}
