name: "Release"

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true

jobs:
  build-matrix:
    uses: ./.github/workflows/build-matrix.yml

  release:
    needs:
      - build-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.build-matrix.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.attr }}
          path: ${{ matrix.attr }}.zip

      - uses: svenstaro/upload-release-action@v2
        with:
          asset_name: ${{ matrix.attr }}-${{ inputs.version }}.zip
          file: ${{ matrix.attr }}.zip
          repo_token: ${{ github.token }}
          tag: ${{ inputs.version }}
