name: "Release (stable)"

on:
  workflow_dispatch:

concurrency:
  group: "release-stable"
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semver.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: nguyenvukhang/semver-increment@v1
        id: semver
        with:
          increment: "patch"
          version-file: "Cargo.toml"
          version-regex: '^version = "(.*)"'

      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "chore: bump ${{ steps.semver.outputs.version }}"
          git tag v${{ steps.semver.outputs.version }}

          git checkout beta
          git merge main

          git checkout stable
          git merge main

          git push --tags
