name: "Release"

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true

jobs:
  nix-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - id: set-matrix
        run: |
          matrix=$(nix eval --json .#githubActions.matrix)
          echo matrix=$matrix >> $GITHUB_OUTPUT

  release:
    needs:
      - nix-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.nix-matrix.outputs.matrix) }}
    name: ${{ matrix.attr }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: Swatinem/rust-cache@v2
      - run: nix build .?submodules=1#packages.${{ matrix.attr }}
      - run: zip -r ${{ matrix.attr }}.zip result/bin
      - uses: svenstaro/upload-release-action@v2
        with:
          asset_name: ${{ matrix.attr }}-${{ inputs.tag }}.zip
          file: ${{ matrix.attr }}.zip
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ inputs.tag }}
