name: "Release"

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true

jobs:
  upload-release:
    runs-on: ubuntu-latest
    steps:
      - id: release-notes
        uses: RedCrafter07/release-notes-action@v1.0.0
        with:
          tag-name: ${{ inputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v4

      - name: Add version to file names
        run: |
          for file in *; do
            mv "$file" "${file}-${{ inputs.version }}"
          done

          echo "Directory contents:"
          ls -la

      - uses: ncipollo/release-action@v1
        with:
          artifacts: ./*
          body: ${{ steps.release-notes.outputs.release-notes }}
          prerelease: ${{ contains(inputs.version, 'beta') }}
          tag: ${{ inputs.version }}
