name: "Release"

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true

jobs:
  upload-release:
    runs-on: ubuntu-latest
    steps:
      - id: release-notes
        uses: RedCrafter07/release-notes-action@v1.0.0
        with:
          tag-name: ${{ inputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v4

      - name: Add version to file names
        run: |
          for file in *; do
            echo "Renaming $file"
            mv "$file" "${file}-${{ inputs.version }}"
          done

          echo "Done"
          ls

      - uses: svenstaro/upload-release-action@v2
        with:
          body: ${{ steps.release-notes.outputs.release-notes }}
          file: ./*
          file_glob: true
          prerelease: ${{ contains(inputs.version, 'beta') }}
          repo_token: ${{ github.token }}
          tag: ${{ inputs.version }}
