name: "Release (beta)"

on:
  workflow_dispatch:

concurrency:
  group: "release-beta"
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semver.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: nguyenvukhang/semver-increment@v1
        id: semver
        with:
          increment: "prerelease"
          identifier: "beta"
          version-file: "Cargo.toml"
          version-regex: '^version = "(.*)"'
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix develop -c cargo metadata # Force Cargo.lock to update
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "chore: bump ${{ steps.semver.outputs.version }}"
          tag: v${{ steps.semver.outputs.version }}
      - uses: devmasx/merge-branch@v1.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: beta
          message: "chore: merge ${{ steps.semver.outputs.version }}"
          type: now
      - uses: ./.github/workflows/build.yml
      - uses: ./.github/workflows/deploy-beta.yml
