name: "Version (beta)"

on:
  workflow_call:
    inputs:
      increment:
        required: true
        type: string

concurrency:
  group: "version-beta"
  cancel-in-progress: false

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semver.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: semver
        uses: nguyenvukhang/semver-increment@v1
        with:
          increment: pre${{ inputs.increment }}
          identifier: "beta"
          version-file: "Cargo.toml"
          version-regex: '^version = "(.*)"'
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix develop -c cargo metadata # Force Cargo.lock to update
      - id: commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "chore: bump ${{ steps.semver.outputs.version }}"
          tag: v${{ steps.semver.outputs.version }}
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_ref: ${{ steps.commit.outputs.commit_long_sha }}
          target_branch: beta

  release:
    needs:
      - version
    uses: ./.github/workflows/release.yml

  deploy:
    needs:
      - release
    uses: ./.github/workflows/deploy-beta.yml
