name: Version (minor)

on:
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: cargo install gbump
      - run: gpump minor -t
        id: bump
      - uses: EndBug/add-and-commit@v9
        with:
          message: "chore: bump ${{ steps.bump.outputs }}"
          default_author: github_actions
