name: "Version"

on:
  workflow_dispatch:
    inputs:
      increment:
        required: true
        type: choice
        options:
          - prerelease
          - preminor
          - stable

env:
  CHANNEL: ${{ inputs.increment == 'stable' && 'stable' || 'beta' }}

concurrency:
  group: "version"
  cancel-in-progress: false

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semver.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: semver
        uses: nguyenvukhang/semver-increment@v1
        with:
          increment: ${{ inputs.increment == 'stable' && 'patch' || inputs.increment }}
          identifier: "beta"
          version-file: "Cargo.toml"
          version-regex: '^version = "(.*)"'

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix develop -c cargo metadata # Force Cargo.lock to update

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "chore: bump ${{ steps.semver.outputs.version }}"
          tag: v${{ steps.semver.outputs.version }}

      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token}}
          source_ref: ${{ github.ref }}
          target_branch: ${{ env.CHANNEL }}

  release:
    needs:
      - version
    uses: ./.github/workflows/release.yml

  deploy:
    needs:
      - release
    uses: ./.github/workflows/deploy.yml
    with:
      channel: $CHANNEL
