name: "Version"

on:
  workflow_dispatch:
    inputs:
      increment:
        description: "The type of version increment"
        required: true
        type: choice
        options:
          - prerelease
          - preminor
          - stable

concurrency:
  group: "version"
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs:
      - build
    uses: ./.github/workflows/deploy.yml
    with:
      channel: ${{ inputs.increment == 'stable' && 'stable' || 'beta' }}

  version:
    needs:
      - deploy
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semver.outputs.version }}
    env:
      TARGET_BRANCH: ${{ inputs.increment == 'stable' && 'stable' || 'beta' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: semver
        uses: nguyenvukhang/semver-increment@v1
        with:
          increment: ${{ inputs.increment == 'stable' && 'patch' || inputs.increment }}
          identifier: "beta"
          version-file: "Cargo.toml"
          version-regex: '^version = "(.*)"'

      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo metadata # Force Cargo.lock to update

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "chore: bump ${{ steps.semver.outputs.version }}"
          tag: v${{ steps.semver.outputs.version }}

      - name: Create branch if it doesn't exist
        run: |
          git fetch origin ${{ env.TARGET_BRANCH }} || git checkout -b ${{ env.TARGET_BRANCH }}
          git push origin ${{ env.TARGET_BRANCH }} || echo "Branch already exists"

      - uses: everlytic/branch-merge@1.1.5
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: ${{ env.TARGET_BRANCH }}

  release:
    needs:
      - version
    uses: ./.github/workflows/release.yml
    with:
      version: v${{ needs.version.outputs.version }}
