[package]
name = "unavi-log"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
tracing.workspace = true
wit-bindgen-rt.workspace = true

[package.metadata.component]
package = "unavi:log"
